; Auto-generated. Do not edit!


(cl:in-package mhri_msgs-msg)


;//! \htmlinclude WaitEventFeedback.msg.html

(cl:defclass <WaitEventFeedback> (roslisp-msg-protocol:ros-message)
  ((is_waiting
    :reader is_waiting
    :initarg :is_waiting
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass WaitEventFeedback (<WaitEventFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WaitEventFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WaitEventFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mhri_msgs-msg:<WaitEventFeedback> is deprecated: use mhri_msgs-msg:WaitEventFeedback instead.")))

(cl:ensure-generic-function 'is_waiting-val :lambda-list '(m))
(cl:defmethod is_waiting-val ((m <WaitEventFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mhri_msgs-msg:is_waiting-val is deprecated.  Use mhri_msgs-msg:is_waiting instead.")
  (is_waiting m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WaitEventFeedback>) ostream)
  "Serializes a message object of type '<WaitEventFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'is_waiting) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WaitEventFeedback>) istream)
  "Deserializes a message object of type '<WaitEventFeedback>"
    (cl:setf (cl:slot-value msg 'is_waiting) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WaitEventFeedback>)))
  "Returns string type for a message object of type '<WaitEventFeedback>"
  "mhri_msgs/WaitEventFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WaitEventFeedback)))
  "Returns string type for a message object of type 'WaitEventFeedback"
  "mhri_msgs/WaitEventFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WaitEventFeedback>)))
  "Returns md5sum for a message object of type '<WaitEventFeedback>"
  "77fd87dc2e06faf5a4acba67f1e878bc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WaitEventFeedback)))
  "Returns md5sum for a message object of type 'WaitEventFeedback"
  "77fd87dc2e06faf5a4acba67f1e878bc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WaitEventFeedback>)))
  "Returns full string definition for message of type '<WaitEventFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# No Feedback~%bool is_waiting~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WaitEventFeedback)))
  "Returns full string definition for message of type 'WaitEventFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# No Feedback~%bool is_waiting~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WaitEventFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WaitEventFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'WaitEventFeedback
    (cl:cons ':is_waiting (is_waiting msg))
))
