// Generated by gencpp from file opt_msgs/IDArray.msg
// DO NOT EDIT!


#ifndef OPT_MSGS_MESSAGE_IDARRAY_H
#define OPT_MSGS_MESSAGE_IDARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace opt_msgs
{
template <class ContainerAllocator>
struct IDArray_
{
  typedef IDArray_<ContainerAllocator> Type;

  IDArray_()
    : header()
    , max_ID(0)
    , ids()  {
    }
  IDArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , max_ID(0)
    , ids(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _max_ID_type;
  _max_ID_type max_ID;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _ids_type;
  _ids_type ids;




  typedef boost::shared_ptr< ::opt_msgs::IDArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opt_msgs::IDArray_<ContainerAllocator> const> ConstPtr;

}; // struct IDArray_

typedef ::opt_msgs::IDArray_<std::allocator<void> > IDArray;

typedef boost::shared_ptr< ::opt_msgs::IDArray > IDArrayPtr;
typedef boost::shared_ptr< ::opt_msgs::IDArray const> IDArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opt_msgs::IDArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opt_msgs::IDArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'opt_msgs': ['/home/hri/catkin_ws/src/openptrack/opt_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opt_msgs::IDArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opt_msgs::IDArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt_msgs::IDArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt_msgs::IDArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt_msgs::IDArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt_msgs::IDArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opt_msgs::IDArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6350c31418d1b806fefd5d37eea32352";
  }

  static const char* value(const ::opt_msgs::IDArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6350c31418d1b806ULL;
  static const uint64_t static_value2 = 0xfefd5d37eea32352ULL;
};

template<class ContainerAllocator>
struct DataType< ::opt_msgs::IDArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opt_msgs/IDArray";
  }

  static const char* value(const ::opt_msgs::IDArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opt_msgs::IDArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 max_ID\n\
int32[] ids\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::opt_msgs::IDArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opt_msgs::IDArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.max_ID);
      stream.next(m.ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IDArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opt_msgs::IDArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opt_msgs::IDArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "max_ID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_ID);
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPT_MSGS_MESSAGE_IDARRAY_H
