// Generated by gencpp from file opt_msgs/OPTTransform.msg
// DO NOT EDIT!


#ifndef OPT_MSGS_MESSAGE_OPTTRANSFORM_H
#define OPT_MSGS_MESSAGE_OPTTRANSFORM_H

#include <ros/service_traits.h>


#include <opt_msgs/OPTTransformRequest.h>
#include <opt_msgs/OPTTransformResponse.h>


namespace opt_msgs
{

struct OPTTransform
{

typedef OPTTransformRequest Request;
typedef OPTTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OPTTransform
} // namespace opt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::opt_msgs::OPTTransform > {
  static const char* value()
  {
    return "c280824f01567ccd998b38545c5bda8d";
  }

  static const char* value(const ::opt_msgs::OPTTransform&) { return value(); }
};

template<>
struct DataType< ::opt_msgs::OPTTransform > {
  static const char* value()
  {
    return "opt_msgs/OPTTransform";
  }

  static const char* value(const ::opt_msgs::OPTTransform&) { return value(); }
};


// service_traits::MD5Sum< ::opt_msgs::OPTTransformRequest> should match 
// service_traits::MD5Sum< ::opt_msgs::OPTTransform > 
template<>
struct MD5Sum< ::opt_msgs::OPTTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::opt_msgs::OPTTransform >::value();
  }
  static const char* value(const ::opt_msgs::OPTTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::opt_msgs::OPTTransformRequest> should match 
// service_traits::DataType< ::opt_msgs::OPTTransform > 
template<>
struct DataType< ::opt_msgs::OPTTransformRequest>
{
  static const char* value()
  {
    return DataType< ::opt_msgs::OPTTransform >::value();
  }
  static const char* value(const ::opt_msgs::OPTTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::opt_msgs::OPTTransformResponse> should match 
// service_traits::MD5Sum< ::opt_msgs::OPTTransform > 
template<>
struct MD5Sum< ::opt_msgs::OPTTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::opt_msgs::OPTTransform >::value();
  }
  static const char* value(const ::opt_msgs::OPTTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::opt_msgs::OPTTransformResponse> should match 
// service_traits::DataType< ::opt_msgs::OPTTransform > 
template<>
struct DataType< ::opt_msgs::OPTTransformResponse>
{
  static const char* value()
  {
    return DataType< ::opt_msgs::OPTTransform >::value();
  }
  static const char* value(const ::opt_msgs::OPTTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPT_MSGS_MESSAGE_OPTTRANSFORM_H
