// Generated by gencpp from file opt_msgs/RoiRect.msg
// DO NOT EDIT!


#ifndef OPT_MSGS_MESSAGE_ROIRECT_H
#define OPT_MSGS_MESSAGE_ROIRECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opt_msgs
{
template <class ContainerAllocator>
struct RoiRect_
{
  typedef RoiRect_<ContainerAllocator> Type;

  RoiRect_()
    : x(0)
    , y(0)
    , width(0)
    , height(0)
    , label(0)
    , confidence(0.0)  {
    }
  RoiRect_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , width(0)
    , height(0)
    , label(0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _label_type;
  _label_type label;

   typedef double _confidence_type;
  _confidence_type confidence;




  typedef boost::shared_ptr< ::opt_msgs::RoiRect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opt_msgs::RoiRect_<ContainerAllocator> const> ConstPtr;

}; // struct RoiRect_

typedef ::opt_msgs::RoiRect_<std::allocator<void> > RoiRect;

typedef boost::shared_ptr< ::opt_msgs::RoiRect > RoiRectPtr;
typedef boost::shared_ptr< ::opt_msgs::RoiRect const> RoiRectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opt_msgs::RoiRect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opt_msgs::RoiRect_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'opt_msgs': ['/home/hri/catkin_ws/src/openptrack/opt_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opt_msgs::RoiRect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opt_msgs::RoiRect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt_msgs::RoiRect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt_msgs::RoiRect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt_msgs::RoiRect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt_msgs::RoiRect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opt_msgs::RoiRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6592653c9982173a3f675f0cad0a0c00";
  }

  static const char* value(const ::opt_msgs::RoiRect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6592653c9982173aULL;
  static const uint64_t static_value2 = 0x3f675f0cad0a0c00ULL;
};

template<class ContainerAllocator>
struct DataType< ::opt_msgs::RoiRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opt_msgs/RoiRect";
  }

  static const char* value(const ::opt_msgs::RoiRect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opt_msgs::RoiRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 width\n\
int32 height\n\
int32 label \n\
float64 confidence \n\
";
  }

  static const char* value(const ::opt_msgs::RoiRect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opt_msgs::RoiRect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.label);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoiRect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opt_msgs::RoiRect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opt_msgs::RoiRect_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "label: ";
    Printer<int32_t>::stream(s, indent + "  ", v.label);
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPT_MSGS_MESSAGE_ROIRECT_H
