// Generated by gencpp from file opt_msgs/TrackArray.msg
// DO NOT EDIT!


#ifndef OPT_MSGS_MESSAGE_TRACKARRAY_H
#define OPT_MSGS_MESSAGE_TRACKARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <opt_msgs/Track.h>

namespace opt_msgs
{
template <class ContainerAllocator>
struct TrackArray_
{
  typedef TrackArray_<ContainerAllocator> Type;

  TrackArray_()
    : header()
    , tracks()  {
    }
  TrackArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tracks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::opt_msgs::Track_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::opt_msgs::Track_<ContainerAllocator> >::other >  _tracks_type;
  _tracks_type tracks;




  typedef boost::shared_ptr< ::opt_msgs::TrackArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opt_msgs::TrackArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrackArray_

typedef ::opt_msgs::TrackArray_<std::allocator<void> > TrackArray;

typedef boost::shared_ptr< ::opt_msgs::TrackArray > TrackArrayPtr;
typedef boost::shared_ptr< ::opt_msgs::TrackArray const> TrackArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opt_msgs::TrackArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opt_msgs::TrackArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'opt_msgs': ['/home/hri/catkin_ws/src/openptrack/opt_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opt_msgs::TrackArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opt_msgs::TrackArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt_msgs::TrackArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt_msgs::TrackArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt_msgs::TrackArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt_msgs::TrackArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opt_msgs::TrackArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4106b2da5c66b9f239aada7912e67b8f";
  }

  static const char* value(const ::opt_msgs::TrackArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4106b2da5c66b9f2ULL;
  static const uint64_t static_value2 = 0x39aada7912e67b8fULL;
};

template<class ContainerAllocator>
struct DataType< ::opt_msgs::TrackArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opt_msgs/TrackArray";
  }

  static const char* value(const ::opt_msgs::TrackArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opt_msgs::TrackArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
opt_msgs/Track[] tracks\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: opt_msgs/Track\n\
uint8 VISIBLE = 0\n\
uint8 OCCLUDED = 1\n\
uint8 NOT_VISIBLE = 2\n\
\n\
int32 id\n\
\n\
float64 x\n\
float64 y\n\
float64 height\n\
float64 distance\n\
float64 age\n\
float64 confidence\n\
\n\
uint8 visibility\n\
\n\
opt_msgs/BoundingBox2D box_2D\n\
\n\
\n\
================================================================================\n\
MSG: opt_msgs/BoundingBox2D\n\
int32 x\n\
int32 y\n\
int32 width\n\
int32 height\n\
";
  }

  static const char* value(const ::opt_msgs::TrackArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opt_msgs::TrackArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tracks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opt_msgs::TrackArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opt_msgs::TrackArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tracks[]" << std::endl;
    for (size_t i = 0; i < v.tracks.size(); ++i)
    {
      s << indent << "  tracks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::opt_msgs::Track_<ContainerAllocator> >::stream(s, indent + "    ", v.tracks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPT_MSGS_MESSAGE_TRACKARRAY_H
