// Generated by gencpp from file mhri_msgs/ForwardingEvent.msg
// DO NOT EDIT!


#ifndef MHRI_MSGS_MESSAGE_FORWARDINGEVENT_H
#define MHRI_MSGS_MESSAGE_FORWARDINGEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mhri_msgs
{
template <class ContainerAllocator>
struct ForwardingEvent_
{
  typedef ForwardingEvent_<ContainerAllocator> Type;

  ForwardingEvent_()
    : header()
    , event()
    , by()  {
    }
  ForwardingEvent_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , event(_alloc)
    , by(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _event_type;
  _event_type event;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _by_type;
  _by_type by;




  typedef boost::shared_ptr< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> const> ConstPtr;

}; // struct ForwardingEvent_

typedef ::mhri_msgs::ForwardingEvent_<std::allocator<void> > ForwardingEvent;

typedef boost::shared_ptr< ::mhri_msgs::ForwardingEvent > ForwardingEventPtr;
typedef boost::shared_ptr< ::mhri_msgs::ForwardingEvent const> ForwardingEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mhri_msgs::ForwardingEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mhri_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'mhri_msgs': ['/home/hri/catkin_ws/src/mhri_workspace/mhri/mhri_msgs/msg', '/home/hri/catkin_ws/devel/.private/mhri_msgs/share/mhri_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76aa3c5d305a1516168ca9a399afd13e";
  }

  static const char* value(const ::mhri_msgs::ForwardingEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76aa3c5d305a1516ULL;
  static const uint64_t static_value2 = 0x168ca9a399afd13eULL;
};

template<class ContainerAllocator>
struct DataType< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mhri_msgs/ForwardingEvent";
  }

  static const char* value(const ::mhri_msgs::ForwardingEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string event\n\
string by\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mhri_msgs::ForwardingEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.event);
      stream.next(m.by);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForwardingEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mhri_msgs::ForwardingEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mhri_msgs::ForwardingEvent_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "event: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.event);
    s << indent << "by: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.by);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MHRI_MSGS_MESSAGE_FORWARDINGEVENT_H
