// Generated by gencpp from file mhri_msgs/LogItem.msg
// DO NOT EDIT!


#ifndef MHRI_MSGS_MESSAGE_LOGITEM_H
#define MHRI_MSGS_MESSAGE_LOGITEM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mhri_msgs
{
template <class ContainerAllocator>
struct LogItem_
{
  typedef LogItem_<ContainerAllocator> Type;

  LogItem_()
    : header()
    , log_items()  {
    }
  LogItem_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , log_items(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _log_items_type;
  _log_items_type log_items;




  typedef boost::shared_ptr< ::mhri_msgs::LogItem_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mhri_msgs::LogItem_<ContainerAllocator> const> ConstPtr;

}; // struct LogItem_

typedef ::mhri_msgs::LogItem_<std::allocator<void> > LogItem;

typedef boost::shared_ptr< ::mhri_msgs::LogItem > LogItemPtr;
typedef boost::shared_ptr< ::mhri_msgs::LogItem const> LogItemConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mhri_msgs::LogItem_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mhri_msgs::LogItem_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mhri_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'mhri_msgs': ['/home/hri/catkin_ws/src/mhri_workspace/mhri/mhri_msgs/msg', '/home/hri/catkin_ws/devel/.private/mhri_msgs/share/mhri_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mhri_msgs::LogItem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mhri_msgs::LogItem_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mhri_msgs::LogItem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mhri_msgs::LogItem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mhri_msgs::LogItem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mhri_msgs::LogItem_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mhri_msgs::LogItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aaf48b26b23ff34c15cbd2fbf907723f";
  }

  static const char* value(const ::mhri_msgs::LogItem_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaaf48b26b23ff34cULL;
  static const uint64_t static_value2 = 0x15cbd2fbf907723fULL;
};

template<class ContainerAllocator>
struct DataType< ::mhri_msgs::LogItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mhri_msgs/LogItem";
  }

  static const char* value(const ::mhri_msgs::LogItem_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mhri_msgs::LogItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string[] log_items\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mhri_msgs::LogItem_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mhri_msgs::LogItem_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.log_items);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LogItem_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mhri_msgs::LogItem_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mhri_msgs::LogItem_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "log_items[]" << std::endl;
    for (size_t i = 0; i < v.log_items.size(); ++i)
    {
      s << indent << "  log_items[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.log_items[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MHRI_MSGS_MESSAGE_LOGITEM_H
