// Generated by gencpp from file mhri_msgs/ReloadWithResultRequest.msg
// DO NOT EDIT!


#ifndef MHRI_MSGS_MESSAGE_RELOADWITHRESULTREQUEST_H
#define MHRI_MSGS_MESSAGE_RELOADWITHRESULTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mhri_msgs
{
template <class ContainerAllocator>
struct ReloadWithResultRequest_
{
  typedef ReloadWithResultRequest_<ContainerAllocator> Type;

  ReloadWithResultRequest_()
    : script_path()  {
    }
  ReloadWithResultRequest_(const ContainerAllocator& _alloc)
    : script_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _script_path_type;
  _script_path_type script_path;




  typedef boost::shared_ptr< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReloadWithResultRequest_

typedef ::mhri_msgs::ReloadWithResultRequest_<std::allocator<void> > ReloadWithResultRequest;

typedef boost::shared_ptr< ::mhri_msgs::ReloadWithResultRequest > ReloadWithResultRequestPtr;
typedef boost::shared_ptr< ::mhri_msgs::ReloadWithResultRequest const> ReloadWithResultRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mhri_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'mhri_msgs': ['/home/hri/catkin_ws/src/mhri_workspace/mhri/mhri_msgs/msg', '/home/hri/catkin_ws/devel/.private/mhri_msgs/share/mhri_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33ad68da42ba9f7bb22ed36417a5ce00";
  }

  static const char* value(const ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33ad68da42ba9f7bULL;
  static const uint64_t static_value2 = 0xb22ed36417a5ce00ULL;
};

template<class ContainerAllocator>
struct DataType< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mhri_msgs/ReloadWithResultRequest";
  }

  static const char* value(const ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string script_path\n\
";
  }

  static const char* value(const ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.script_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReloadWithResultRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mhri_msgs::ReloadWithResultRequest_<ContainerAllocator>& v)
  {
    s << indent << "script_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.script_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MHRI_MSGS_MESSAGE_RELOADWITHRESULTREQUEST_H
