// Generated by gencpp from file mhri_msgs/RenderSceneFeedback.msg
// DO NOT EDIT!


#ifndef MHRI_MSGS_MESSAGE_RENDERSCENEFEEDBACK_H
#define MHRI_MSGS_MESSAGE_RENDERSCENEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mhri_msgs
{
template <class ContainerAllocator>
struct RenderSceneFeedback_
{
  typedef RenderSceneFeedback_<ContainerAllocator> Type;

  RenderSceneFeedback_()
    : is_rendering(false)  {
    }
  RenderSceneFeedback_(const ContainerAllocator& _alloc)
    : is_rendering(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_rendering_type;
  _is_rendering_type is_rendering;




  typedef boost::shared_ptr< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct RenderSceneFeedback_

typedef ::mhri_msgs::RenderSceneFeedback_<std::allocator<void> > RenderSceneFeedback;

typedef boost::shared_ptr< ::mhri_msgs::RenderSceneFeedback > RenderSceneFeedbackPtr;
typedef boost::shared_ptr< ::mhri_msgs::RenderSceneFeedback const> RenderSceneFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mhri_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'mhri_msgs': ['/home/hri/catkin_ws/src/mhri_workspace/mhri/mhri_msgs/msg', '/home/hri/catkin_ws/devel/.private/mhri_msgs/share/mhri_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d20ec80974a56e3140ebf7d3d745948";
  }

  static const char* value(const ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d20ec80974a56e3ULL;
  static const uint64_t static_value2 = 0x140ebf7d3d745948ULL;
};

template<class ContainerAllocator>
struct DataType< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mhri_msgs/RenderSceneFeedback";
  }

  static const char* value(const ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool is_rendering\n\
\n\
";
  }

  static const char* value(const ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_rendering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RenderSceneFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mhri_msgs::RenderSceneFeedback_<ContainerAllocator>& v)
  {
    s << indent << "is_rendering: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_rendering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MHRI_MSGS_MESSAGE_RENDERSCENEFEEDBACK_H
