; Auto-generated. Do not edit!


(cl:in-package calibration_msgs-msg)


;//! \htmlinclude CheckerboardExtractionFeedback.msg.html

(cl:defclass <CheckerboardExtractionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass CheckerboardExtractionFeedback (<CheckerboardExtractionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CheckerboardExtractionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CheckerboardExtractionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name calibration_msgs-msg:<CheckerboardExtractionFeedback> is deprecated: use calibration_msgs-msg:CheckerboardExtractionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CheckerboardExtractionFeedback>) ostream)
  "Serializes a message object of type '<CheckerboardExtractionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CheckerboardExtractionFeedback>) istream)
  "Deserializes a message object of type '<CheckerboardExtractionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CheckerboardExtractionFeedback>)))
  "Returns string type for a message object of type '<CheckerboardExtractionFeedback>"
  "calibration_msgs/CheckerboardExtractionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CheckerboardExtractionFeedback)))
  "Returns string type for a message object of type 'CheckerboardExtractionFeedback"
  "calibration_msgs/CheckerboardExtractionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CheckerboardExtractionFeedback>)))
  "Returns md5sum for a message object of type '<CheckerboardExtractionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CheckerboardExtractionFeedback)))
  "Returns md5sum for a message object of type 'CheckerboardExtractionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CheckerboardExtractionFeedback>)))
  "Returns full string definition for message of type '<CheckerboardExtractionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CheckerboardExtractionFeedback)))
  "Returns full string definition for message of type 'CheckerboardExtractionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CheckerboardExtractionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CheckerboardExtractionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CheckerboardExtractionFeedback
))
