(cl:defpackage polly_speech-msg
  (:use )
  (:export
   "<SPEECHACTION>"
   "SPEECHACTION"
   "<SPEECHACTIONFEEDBACK>"
   "SPEECHACTIONFEEDBACK"
   "<SPEECHACTIONGOAL>"
   "SPEECHACTIONGOAL"
   "<SPEECHACTIONRESULT>"
   "SPEECHACTIONRESULT"
   "<SPEECHFEEDBACK>"
   "SPEECHFEEDBACK"
   "<SPEECHGOAL>"
   "SPEECHGOAL"
   "<SPEECHRESULT>"
   "SPEECHRESULT"
  ))

