// Generated by gencpp from file mhri_social_msgs/FaceDetection3D.msg
// DO NOT EDIT!


#ifndef MHRI_SOCIAL_MSGS_MESSAGE_FACEDETECTION3D_H
#define MHRI_SOCIAL_MSGS_MESSAGE_FACEDETECTION3D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>
#include <sensor_msgs/Image.h>

namespace mhri_social_msgs
{
template <class ContainerAllocator>
struct FaceDetection3D_
{
  typedef FaceDetection3D_<ContainerAllocator> Type;

  FaceDetection3D_()
    : num_of_detected(0)
    , faces_pose()
    , faces_image()  {
    }
  FaceDetection3D_(const ContainerAllocator& _alloc)
    : num_of_detected(0)
    , faces_pose(_alloc)
    , faces_image(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _num_of_detected_type;
  _num_of_detected_type num_of_detected;

   typedef std::vector< ::geometry_msgs::PointStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PointStamped_<ContainerAllocator> >::other >  _faces_pose_type;
  _faces_pose_type faces_pose;

   typedef std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::Image_<ContainerAllocator> >::other >  _faces_image_type;
  _faces_image_type faces_image;




  typedef boost::shared_ptr< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> const> ConstPtr;

}; // struct FaceDetection3D_

typedef ::mhri_social_msgs::FaceDetection3D_<std::allocator<void> > FaceDetection3D;

typedef boost::shared_ptr< ::mhri_social_msgs::FaceDetection3D > FaceDetection3DPtr;
typedef boost::shared_ptr< ::mhri_social_msgs::FaceDetection3D const> FaceDetection3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mhri_social_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mhri_social_msgs': ['/home/hri/catkin_ws/src/mhri_workspace/mhri_social_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "038b473215491c8276c651727ebdf695";
  }

  static const char* value(const ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x038b473215491c82ULL;
  static const uint64_t static_value2 = 0x76c651727ebdf695ULL;
};

template<class ContainerAllocator>
struct DataType< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mhri_social_msgs/FaceDetection3D";
  }

  static const char* value(const ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num_of_detected\n\
geometry_msgs/PointStamped[] faces_pose\n\
sensor_msgs/Image[] faces_image\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
";
  }

  static const char* value(const ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_of_detected);
      stream.next(m.faces_pose);
      stream.next(m.faces_image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceDetection3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mhri_social_msgs::FaceDetection3D_<ContainerAllocator>& v)
  {
    s << indent << "num_of_detected: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_of_detected);
    s << indent << "faces_pose[]" << std::endl;
    for (size_t i = 0; i < v.faces_pose.size(); ++i)
    {
      s << indent << "  faces_pose[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.faces_pose[i]);
    }
    s << indent << "faces_image[]" << std::endl;
    for (size_t i = 0; i < v.faces_image.size(); ++i)
    {
      s << indent << "  faces_image[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "    ", v.faces_image[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MHRI_SOCIAL_MSGS_MESSAGE_FACEDETECTION3D_H
