(cl:defpackage calibration_msgs-srv
  (:use )
  (:export
   "GETCALIBRATIONRESULTS"
   "<GETCALIBRATIONRESULTS-REQUEST>"
   "GETCALIBRATIONRESULTS-REQUEST"
   "<GETCALIBRATIONRESULTS-RESPONSE>"
   "GETCALIBRATIONRESULTS-RESPONSE"
   "GETDEVICEINFO"
   "<GETDEVICEINFO-REQUEST>"
   "GETDEVICEINFO-REQUEST"
   "<GETDEVICEINFO-RESPONSE>"
   "GETDEVICEINFO-RESPONSE"
  ))

