// Generated by gencpp from file calibration_msgs/GetCalibrationResults.msg
// DO NOT EDIT!


#ifndef CALIBRATION_MSGS_MESSAGE_GETCALIBRATIONRESULTS_H
#define CALIBRATION_MSGS_MESSAGE_GETCALIBRATIONRESULTS_H

#include <ros/service_traits.h>


#include <calibration_msgs/GetCalibrationResultsRequest.h>
#include <calibration_msgs/GetCalibrationResultsResponse.h>


namespace calibration_msgs
{

struct GetCalibrationResults
{

typedef GetCalibrationResultsRequest Request;
typedef GetCalibrationResultsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCalibrationResults
} // namespace calibration_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::calibration_msgs::GetCalibrationResults > {
  static const char* value()
  {
    return "0bbbf0e9d4af3cb89da005d0841c9f95";
  }

  static const char* value(const ::calibration_msgs::GetCalibrationResults&) { return value(); }
};

template<>
struct DataType< ::calibration_msgs::GetCalibrationResults > {
  static const char* value()
  {
    return "calibration_msgs/GetCalibrationResults";
  }

  static const char* value(const ::calibration_msgs::GetCalibrationResults&) { return value(); }
};


// service_traits::MD5Sum< ::calibration_msgs::GetCalibrationResultsRequest> should match 
// service_traits::MD5Sum< ::calibration_msgs::GetCalibrationResults > 
template<>
struct MD5Sum< ::calibration_msgs::GetCalibrationResultsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::calibration_msgs::GetCalibrationResults >::value();
  }
  static const char* value(const ::calibration_msgs::GetCalibrationResultsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::calibration_msgs::GetCalibrationResultsRequest> should match 
// service_traits::DataType< ::calibration_msgs::GetCalibrationResults > 
template<>
struct DataType< ::calibration_msgs::GetCalibrationResultsRequest>
{
  static const char* value()
  {
    return DataType< ::calibration_msgs::GetCalibrationResults >::value();
  }
  static const char* value(const ::calibration_msgs::GetCalibrationResultsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::calibration_msgs::GetCalibrationResultsResponse> should match 
// service_traits::MD5Sum< ::calibration_msgs::GetCalibrationResults > 
template<>
struct MD5Sum< ::calibration_msgs::GetCalibrationResultsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::calibration_msgs::GetCalibrationResults >::value();
  }
  static const char* value(const ::calibration_msgs::GetCalibrationResultsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::calibration_msgs::GetCalibrationResultsResponse> should match 
// service_traits::DataType< ::calibration_msgs::GetCalibrationResults > 
template<>
struct DataType< ::calibration_msgs::GetCalibrationResultsResponse>
{
  static const char* value()
  {
    return DataType< ::calibration_msgs::GetCalibrationResults >::value();
  }
  static const char* value(const ::calibration_msgs::GetCalibrationResultsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CALIBRATION_MSGS_MESSAGE_GETCALIBRATIONRESULTS_H
