// Generated by gencpp from file calibration_msgs/GetDeviceInfo.msg
// DO NOT EDIT!


#ifndef CALIBRATION_MSGS_MESSAGE_GETDEVICEINFO_H
#define CALIBRATION_MSGS_MESSAGE_GETDEVICEINFO_H

#include <ros/service_traits.h>


#include <calibration_msgs/GetDeviceInfoRequest.h>
#include <calibration_msgs/GetDeviceInfoResponse.h>


namespace calibration_msgs
{

struct GetDeviceInfo
{

typedef GetDeviceInfoRequest Request;
typedef GetDeviceInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDeviceInfo
} // namespace calibration_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::calibration_msgs::GetDeviceInfo > {
  static const char* value()
  {
    return "da6eb3cec2613536c7b7d4f43941b1a0";
  }

  static const char* value(const ::calibration_msgs::GetDeviceInfo&) { return value(); }
};

template<>
struct DataType< ::calibration_msgs::GetDeviceInfo > {
  static const char* value()
  {
    return "calibration_msgs/GetDeviceInfo";
  }

  static const char* value(const ::calibration_msgs::GetDeviceInfo&) { return value(); }
};


// service_traits::MD5Sum< ::calibration_msgs::GetDeviceInfoRequest> should match 
// service_traits::MD5Sum< ::calibration_msgs::GetDeviceInfo > 
template<>
struct MD5Sum< ::calibration_msgs::GetDeviceInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::calibration_msgs::GetDeviceInfo >::value();
  }
  static const char* value(const ::calibration_msgs::GetDeviceInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::calibration_msgs::GetDeviceInfoRequest> should match 
// service_traits::DataType< ::calibration_msgs::GetDeviceInfo > 
template<>
struct DataType< ::calibration_msgs::GetDeviceInfoRequest>
{
  static const char* value()
  {
    return DataType< ::calibration_msgs::GetDeviceInfo >::value();
  }
  static const char* value(const ::calibration_msgs::GetDeviceInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::calibration_msgs::GetDeviceInfoResponse> should match 
// service_traits::MD5Sum< ::calibration_msgs::GetDeviceInfo > 
template<>
struct MD5Sum< ::calibration_msgs::GetDeviceInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::calibration_msgs::GetDeviceInfo >::value();
  }
  static const char* value(const ::calibration_msgs::GetDeviceInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::calibration_msgs::GetDeviceInfoResponse> should match 
// service_traits::DataType< ::calibration_msgs::GetDeviceInfo > 
template<>
struct DataType< ::calibration_msgs::GetDeviceInfoResponse>
{
  static const char* value()
  {
    return DataType< ::calibration_msgs::GetDeviceInfo >::value();
  }
  static const char* value(const ::calibration_msgs::GetDeviceInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CALIBRATION_MSGS_MESSAGE_GETDEVICEINFO_H
