// Generated by gencpp from file calibration_msgs/Point2DArray.msg
// DO NOT EDIT!


#ifndef CALIBRATION_MSGS_MESSAGE_POINT2DARRAY_H
#define CALIBRATION_MSGS_MESSAGE_POINT2DARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <calibration_msgs/Point2D.h>

namespace calibration_msgs
{
template <class ContainerAllocator>
struct Point2DArray_
{
  typedef Point2DArray_<ContainerAllocator> Type;

  Point2DArray_()
    : header()
    , x_size(0)
    , y_size(0)
    , points()  {
    }
  Point2DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x_size(0)
    , y_size(0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _x_size_type;
  _x_size_type x_size;

   typedef uint32_t _y_size_type;
  _y_size_type y_size;

   typedef std::vector< ::calibration_msgs::Point2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::calibration_msgs::Point2D_<ContainerAllocator> >::other >  _points_type;
  _points_type points;




  typedef boost::shared_ptr< ::calibration_msgs::Point2DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::calibration_msgs::Point2DArray_<ContainerAllocator> const> ConstPtr;

}; // struct Point2DArray_

typedef ::calibration_msgs::Point2DArray_<std::allocator<void> > Point2DArray;

typedef boost::shared_ptr< ::calibration_msgs::Point2DArray > Point2DArrayPtr;
typedef boost::shared_ptr< ::calibration_msgs::Point2DArray const> Point2DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::calibration_msgs::Point2DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::calibration_msgs::Point2DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace calibration_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'calibration_msgs': ['/home/hri/catkin_ws/src/calibration_toolkit/calibration_msgs/msg', '/home/hri/catkin_ws/devel/.private/calibration_msgs/share/calibration_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::calibration_msgs::Point2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calibration_msgs::Point2DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calibration_msgs::Point2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calibration_msgs::Point2DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration_msgs::Point2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration_msgs::Point2DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::calibration_msgs::Point2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6fc044ee7e4eb74354c64672ac779e7";
  }

  static const char* value(const ::calibration_msgs::Point2DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6fc044ee7e4eb74ULL;
  static const uint64_t static_value2 = 0x354c64672ac779e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::calibration_msgs::Point2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calibration_msgs/Point2DArray";
  }

  static const char* value(const ::calibration_msgs::Point2DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::calibration_msgs::Point2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint32 x_size\n\
uint32 y_size\n\
calibration_msgs/Point2D[] points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: calibration_msgs/Point2D\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::calibration_msgs::Point2DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::calibration_msgs::Point2DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x_size);
      stream.next(m.y_size);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point2DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::calibration_msgs::Point2DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::calibration_msgs::Point2DArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x_size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x_size);
    s << indent << "y_size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y_size);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::calibration_msgs::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CALIBRATION_MSGS_MESSAGE_POINT2DARRAY_H
