// Generated by gencpp from file polly_speech/SpeechResult.msg
// DO NOT EDIT!


#ifndef POLLY_SPEECH_MESSAGE_SPEECHRESULT_H
#define POLLY_SPEECH_MESSAGE_SPEECHRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace polly_speech
{
template <class ContainerAllocator>
struct SpeechResult_
{
  typedef SpeechResult_<ContainerAllocator> Type;

  SpeechResult_()
    : result(false)  {
    }
  SpeechResult_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::polly_speech::SpeechResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::polly_speech::SpeechResult_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechResult_

typedef ::polly_speech::SpeechResult_<std::allocator<void> > SpeechResult;

typedef boost::shared_ptr< ::polly_speech::SpeechResult > SpeechResultPtr;
typedef boost::shared_ptr< ::polly_speech::SpeechResult const> SpeechResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::polly_speech::SpeechResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::polly_speech::SpeechResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace polly_speech

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'polly_speech': ['/home/hri/catkin_ws/devel/.private/polly_speech/share/polly_speech/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::polly_speech::SpeechResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::polly_speech::SpeechResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::polly_speech::SpeechResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::polly_speech::SpeechResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::polly_speech::SpeechResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::polly_speech::SpeechResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::polly_speech::SpeechResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::polly_speech::SpeechResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::polly_speech::SpeechResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "polly_speech/SpeechResult";
  }

  static const char* value(const ::polly_speech::SpeechResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::polly_speech::SpeechResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool result\n\
";
  }

  static const char* value(const ::polly_speech::SpeechResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::polly_speech::SpeechResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::polly_speech::SpeechResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::polly_speech::SpeechResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POLLY_SPEECH_MESSAGE_SPEECHRESULT_H
